add heap
elizova/DataStructures pull request #2
Opened 2024-04-01 15:31 UTC by elizova

2024-04-10 11:16 UTC, ostind requested changes
Еще пожелание: спрячь Heap.cpp и Heah.h в папку Heap (или heap), поменяй пути до Heap.cpp в CmakeLists.txt, а сами тесты спрячь в какой нибудь Heap/tests.h, в main заинклудь его, а вызовы оставь

2024-04-10 11:16 UTC, ostind commented on main.cpp
> +    h.print(0, 0);
Спрячь это тоже в тест

2024-04-10 11:16 UTC, ostind commented on Heap.cpp
>  void Heap:: sift_up(int index){
При разрешении пространства имен пробелы не ставят, здесь надо `Heap::sift_up(...)`

2024-04-10 11:18 UTC, ostind commented on Heap.h
> +#define UNTITLED6_HEAP_H
Здесь можно уже поменять на HEAPELIZOVA_HEAP_H или вообще на HEAP_H или удалить `#ifndef #define...#endif` и заменить это строчкой `#pragma once` в начале

2024-04-10 11:28 UTC, elizova commented on main.cpp
> +    h.print(0, 0);
а Heap/tests тоже в отдельную папку heap убирать?

2024-04-10 13:12 UTC, ostind requested changes
Надо потом будет ещё структуру коммитов поменять, пока сделай эти изменения, их можно в одном коммите

2024-04-10 13:12 UTC, ostind commented on Heap/HeapTests.h
> +class Heap_tests{
Пробел забыла перед скобкой
Идея неплохая, но тогда:
1) перенеси в private секцию метод delimiter который у тебя снаружи и вызывай его внутри каждого теста
2) сделай все методы (тесты) внутри статическими (добавь ключевое слово static перед типом возвращаемого значения у каждого метода)

2024-04-10 13:12 UTC, ostind commented on Heap/HeapTests.h
> +    std::vector<int> heap;
Это хранить в классе вообще не нужно, путь в каждом тесте создаётся куча, это нормально, так делают

2024-04-10 13:12 UTC, ostind commented on main.cpp
> +    Heap_tests heap;
Когда все методы сделаешь статическими больше объект создавать не надо будет, можешь сразу вызывать `Heap_tests::test0()` и тд

2024-04-10 23:07 UTC, ostind requested changes

2024-04-10 23:07 UTC, ostind commented on Heap/Heap.cpp
> +}
Перенос строки нужен, отдельный коммит

2024-04-10 23:13 UTC, ostind commented
Еще сделай две вещи:
1) Реализуй конструктор для Heap, который принимает вектор и инициализирует твой внутренний вектор (через initializer_list, почитай про него (например, тут https://www.learncpp.com/cpp-tutorial/constructor-member-initializer-lists/)
2) Напиши тесты
    * генерация масива из миллиона случайных чисел (как положительных, так и отрицательных), поиск максимума в нем руками, а затем вывод heap.top() и сравнение этих двух чисел, должны совпадать
    * удаление из пустой кучи

2024-04-21 05:27 UTC, ostind approved these changes
👍LGTM

2024-04-21 06:29 UTC, merged